server.port: 8082
spring.application.name: bpm-service

eureka:
  client:
    service-url.default-zone: http://localhost:8761/eureka

spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888